# Generated by Django 5.1.2 on 2024-10-20 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_create_at_task_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='username',
            field=models.CharField(default='admin', max_length=200),
            preserve_default=False,
        ),
    ]
